server:
  port: 8003
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到eureka，默认为true
    fetch-registry: true #表示是否从eureka抓取已有的注册信息，默认为true
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: receive8003
    prefer-ip-address: true  #访问路径显示Ip地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端 向服务端发送心跳的时间间隔，默认30s
    lease-expiration-duration-in-seconds: 2 #Eureka服务端收到最后心跳的等待的时间
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:  #表示定义的名称，用于binding集合
          type: rabbit  #消息组件类型
          environment:  #设置RabbitMq相关配置
            spring:
              rabbitmq:
                hosts: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit  #设置要绑定的消息服务的位置
          group:  cloudA