server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:qinixiangyang111/SpringcloudConfig.git #github上面git仓库的名字
          search-paths:
            - SpringcloudConfig  #搜索目录
      label: master #读取分支

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到eureka，默认为true
    fetch-registry: true #表示是否从eureka抓取已有的注册信息，默认为true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
