server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true

#spring GATEWAY  yml配置
spring:
  application:
    name:  cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-05-20T15:27:25.124+08:00[Asia/Shanghai] #这个时间之后才能访问
           # - Before=2020-04-20T15:27:25.124+08:00[Asia/Shanghai] #这个时间之后才能访问
           #- Between=2020-04-20T15:27:25.124+08:00[Asia/Shanghai],2020-04-20T15:27:25.124+08:00[Asia/Shanghai] #这个时间之后才能访问
           # - Cookie=username,zzyy   #curl http://172.16.10.15:9527/payment/lb --cookie "username=zzyy"
            - Header=X-Request-Id, \d+ #curl http://172.16.10.15:9527/payment/lb -H  "X-Request-Id:1234"
           # - Query=username, \d+
           # - Method=GET
            #- Host=*.baidu.com

