server:
  port: 9001

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-service-payment
management:
  endpoints:
    web:
      exposure:
        include: '*'
