server:
  port: 84

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:7003
        port: 8719
  application:
    name: nacos-service-consumer

service-url:
  nacos-user-service: http://nacos-service-payment
#激活sentinel对feign支持
feign:
  sentinel:
    enabled: true
